name = "leptos-cf"
main = "build/_worker.js"
compatibility_date = "2026-04-22"

[build]
command = "bash ./scripts/build-edge.sh"

[assets]
directory = "./target/site"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "leptos-cf-db"
database_id = "00000000-0000-0000-0000-000000000000"
preview_database_id = "00000000-0000-0000-0000-000000000000"
migrations_dir = "migrations"
